cmake_minimum_required(VERSION 3.24)
include(ExternalProject)
include(FetchContent)

# Versions of third party libraries
set(TPV_ZLIB_VER "v1.3.2")
set(TPV_ZIP_VER "v1.12")
set(TPV_SDL_VER "release-3.4.16")
set(TPV_PNG_VER "v1.6.59")
set(TPV_VMA_VER "v3.4.0")
set(TPV_PUGIXML_VER "v1.16")
set(TPV_ZYCORE_VER "v1.5.1")
set(TPV_ZYDIS_VER "v4.1.1")
set(TPV_TRACY_VER "v0.14.1")
set(TPV_MAGICENUM_VER "v0.9.8")
set(TPV_IMGUI_VER "v1.92.9b")
###################################

set(ProjectName psOff_third_party)
project(${ProjectName} VERSION 0.0.1)

set(INSTALL_DIR ${CMAKE_BINARY_DIR}/install)
set(BUILDS_DIR ${CMAKE_BINARY_DIR}/builds)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-strict-aliasing -fno-stack-protector -ffunction-sections")

if(WIN32)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_WIN32_WINNT=0x0A00")
else()
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
endif()

set(CMAKE_C_FLAGS ${CMAKE_CXX_FLAGS})

set(CMAKE_INSTALL_MESSAGE LAZY)

set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
set(CMAKE_WINDOWS_SYMBOL_VISIBILITY_IN_STATIC_LIBRARIES OFF)

find_package(Vulkan 1.4 REQUIRED)

ExternalProject_Add(zlib_project
  GIT_REPOSITORY https://github.com/madler/zlib.git
  GIT_TAG ${TPV_ZLIB_VER}
  GIT_SHALLOW true
  SOURCE_DIR ${CMAKE_SOURCE_DIR}/projects/zlib
  BINARY_DIR ${BUILDS_DIR}/zlib
  CMAKE_ARGS
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}
  -DCMAKE_INSTALL_MESSAGE=${CMAKE_INSTALL_MESSAGE}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
  -DCMAKE_PREFIX_PATH:STRING=${INSTALL_DIR}
)

# SDL3
# APPLY SDL PATCH
ExternalProject_Add(sdl_project
  GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
  GIT_TAG ${TPV_SDL_VER}
  GIT_SHALLOW true
  SOURCE_DIR ${CMAKE_SOURCE_DIR}/projects/SDL
  BINARY_DIR ${BUILDS_DIR}/sdl
  CMAKE_ARGS
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}
  -DCMAKE_INSTALL_MESSAGE=${CMAKE_INSTALL_MESSAGE}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
  -DCMAKE_PREFIX_PATH:STRING=${INSTALL_DIR}

  -DSDL_DIRECTX:BOOL=OFF
  -DSDL_DUMMYVIDEO:BOOL=OFF
  -DSDL_DUMMYCAMERA:BOOL=OFF
  -DSDL_DUMMYAUDIO:BOOL=OFF
  -DSDL_OFFSCREEN:BOOL=OFF
  -DSDL_OPENGL:BOOL=OFF
  -DSDL_OPENGLES:BOOL=OFF
  -DSDL_RENDERER_D3D:BOOL=OFF
  -DSDL_RENDERER_D3D11:BOOL=OFF
  -DSDL_RENDERER_D3D12:BOOL=OFF
  -DSDL_RENDER_GPU:BOOL=OFF
  -DSDL_GPU_D3D12:BOOL=OFF
  -DSDL_TESTS:BOOL=OFF
  -DSDL_TESTS_LINK_SHARED:BOOL=OFF
)

ExternalProject_Add(libpng_project
  GIT_REPOSITORY https://github.com/pnggroup/libpng.git
  GIT_TAG ${TPV_PNG_VER}
  GIT_SHALLOW true
  SOURCE_DIR ${CMAKE_SOURCE_DIR}/projects/libpng
  BINARY_DIR ${BUILDS_DIR}/libpng
  CMAKE_ARGS
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}
  -DCMAKE_INSTALL_MESSAGE=${CMAKE_INSTALL_MESSAGE}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
  -DCMAKE_PREFIX_PATH:STRING=${INSTALL_DIR}

  -DPNG_SHARED:BOOL=OFF
  -DPNG_STATIC:BOOL=ON
  -DPNG_EXECUTABLES:BOOL=ON
  -DPNG_TOOLS:BOOL=OFF
  -DPNG_TESTS:BOOL=OFF
  -DSKIP_INSTALL_ALL:BOOL=OFF
)
ExternalProject_Add_StepDependencies(libpng_project install zlib_project)

install(DIRECTORY "projects/ffmpeg/include/" DESTINATION "${INSTALL_DIR}/include")

install(DIRECTORY "projects/nlohmann/" DESTINATION ${INSTALL_DIR}/include/nlohmann
  FILES_MATCHING PATTERN "*.hpp"
)

install(DIRECTORY "projects/alpaca/include/" DESTINATION ${INSTALL_DIR}/include)
install(DIRECTORY "projects/fixed_containers" DESTINATION "${INSTALL_DIR}/include")
install(DIRECTORY "projects/incbin" DESTINATION "${INSTALL_DIR}/include")
install(DIRECTORY "projects/emhash" DESTINATION "${INSTALL_DIR}/include")
install(DIRECTORY "projects/renderdoc" DESTINATION "${INSTALL_DIR}/include")

ExternalProject_Add(vma_project
  GIT_REPOSITORY https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator.git
  GIT_TAG ${TPV_VMA_VER}
  GIT_SHALLOW true
  SOURCE_DIR ${CMAKE_SOURCE_DIR}/projects/VulkanMemoryAllocator
  BINARY_DIR ${BUILDS_DIR}/vma
  CMAKE_ARGS
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}
  -DCMAKE_INSTALL_MESSAGE=${CMAKE_INSTALL_MESSAGE}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
  -DCMAKE_PREFIX_PATH:STRING=${INSTALL_DIR}
)

install(DIRECTORY "projects/xxhash/include/" DESTINATION ${INSTALL_DIR}/include)

ExternalProject_Add(libzip_project
  GIT_REPOSITORY https://github.com/nih-at/libzip.git
  GIT_TAG ${TPV_ZIP_VER}
  GIT_SHALLOW true
  SOURCE_DIR ${CMAKE_SOURCE_DIR}/projects/libzip
  BINARY_DIR ${BUILDS_DIR}/libzip
  CMAKE_ARGS
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}
  -DCMAKE_INSTALL_MESSAGE=${CMAKE_INSTALL_MESSAGE}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
  -DCMAKE_PREFIX_PATH:STRING=${INSTALL_DIR}

  -DENABLE_COMMONCRYPTO:BOOL=OFF
  -DENABLE_GNUTLS:BOOL=OFF
  -DENABLE_OPENSSL:BOOL=ON
  -DENABLE_FDOPEN:BOOL=OFF
  -DBUILD_TOOLS:BOOL=OFF
  -DBUILD_REGRESS:BOOL=OFF
  -DBUILD_EXAMPLES:BOOL=OFF
  -DBUILD_DOC:BOOL=OFF
  -DENABLE_ZSTD:BOOL=OFF
  -DENABLE_LZMA:BOOL=OFF
  -DENABLE_BZIP2:BOOL=OFF
  -DLIBZIP_DO_INSTALL:BOOL=ON
)
ExternalProject_Add_StepDependencies(libzip_project install zlib_project)

# Should be set up with ./prepare_boost.sh first!
set(BOOST_INCLUDE_LIBRARIES "program_options;chrono;date_time;filesystem;interprocess;stacktrace;uuid;beast;thread;url;asio;dll;process;icl;container;dynamic_bitset")
ExternalProject_Add(boost_project
  SOURCE_DIR ${CMAKE_SOURCE_DIR}/projects/boost
  BINARY_DIR ${BUILDS_DIR}/boost
  CMAKE_ARGS
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_INSTALL_MESSAGE=NEVER
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
  -DCMAKE_PREFIX_PATH:STRING=${INSTALL_DIR}

  -DBoost_USE_STATIC_LIBS=ON
  -DBoost_USE_MULTITHREADED=ON
  -DBUILD_TESTING=OFF
  -DBOOST_INSTALL_LAYOUT=system
  CMAKE_CACHE_ARGS -DBOOST_INCLUDE_LIBRARIES:STRING=${BOOST_INCLUDE_LIBRARIES}
)

ExternalProject_Add(pugixml_project
  GIT_REPOSITORY https://github.com/zeux/pugixml.git
  GIT_TAG ${TPV_PUGIXML_VER}
  GIT_SHALLOW true
  SOURCE_DIR ${CMAKE_SOURCE_DIR}/projects/pugixml
  BINARY_DIR ${BUILDS_DIR}/pugixml
  CMAKE_ARGS
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}
  -DCMAKE_INSTALL_MESSAGE=${CMAKE_INSTALL_MESSAGE}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
  -DCMAKE_PREFIX_PATH:STRING=${INSTALL_DIR}
)

set(ZYCORE_PATH "${CMAKE_SOURCE_DIR}/projects/zycore")
ExternalProject_Add(zydis_core_project
  GIT_REPOSITORY https://github.com/zyantific/zycore-c.git
  GIT_TAG ${TPV_ZYCORE_VER}
  SOURCE_DIR ${ZYCORE_PATH}
  BINARY_DIR ${BUILDS_DIR}/zydis_core
  CMAKE_ARGS
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}
  -DCMAKE_INSTALL_MESSAGE=${CMAKE_INSTALL_MESSAGE}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
  -DCMAKE_PREFIX_PATH:STRING=${INSTALL_DIR}
)

ExternalProject_Add(zydis_project
  GIT_REPOSITORY https://github.com/zyantific/zydis.git
  GIT_TAG ${TPV_ZYDIS_VER}
  GIT_SHALLOW true
  GIT_SUBMODULES ""
  GIT_SUBMODULES_RECURSE false
  SOURCE_DIR ${CMAKE_SOURCE_DIR}/projects/zydis
  BINARY_DIR ${BUILDS_DIR}/zydis
  CMAKE_ARGS
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}
  -DCMAKE_INSTALL_MESSAGE=${CMAKE_INSTALL_MESSAGE}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
  -DCMAKE_PREFIX_PATH:STRING=${INSTALL_DIR}

  -DZYDIS_BUILD_TOOLS:BOOL=OFF
  -DZYDIS_BUILD_EXAMPLES:BOOL=OFF
  -DZYDIS_BUILD_DOXYGEN:BOOL=OFF
  -DZYDIS_BUILD_TESTS:BOOL=OFF
  -DZYAN_ZYCORE_PATH=${ZYCORE_PATH}
)
ExternalProject_Add_StepDependencies(zydis_project install zydis_core_project)

ExternalProject_Add(tracy_project
  GIT_REPOSITORY https://github.com/wolfpld/tracy.git
  GIT_TAG ${TPV_TRACY_VER}
  GIT_SHALLOW true
  SOURCE_DIR ${CMAKE_SOURCE_DIR}/projects/tracy
  BINARY_DIR ${BUILDS_DIR}/tracy
  CMAKE_ARGS
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}
  -DCMAKE_INSTALL_MESSAGE=${CMAKE_INSTALL_MESSAGE}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}

  -DTRACY_ENABLE:BOOL=ON
  -DTRACY_STATIC:BOOL=OFF
  -DTRACY_NO_SAMPLING:BOOL=ON
  -DTRACY_NO_CODE_TRANSFER:BOOL=ON
  -DTRACY_ONLY_LOCALHOST:BOOL=ON
  -DTRACY_ON_DEMAND:BOOL=ON
  -DTRACY_NO_CONTEXT_SWITCH:BOOL=ON
  -DTRACY_NO_CALLSTACK:BOOL=ON
  -DTRACY_NO_SYSTEM_TRACING:BOOL=ON
  -DTRACY_NO_FRAME_IMAGE:BOOL=ON
  -DTRACY_NO_CRASH_HANDLER:BOOL=ON
)

ExternalProject_Add(magic_enum
  GIT_REPOSITORY https://github.com/Neargye/magic_enum.git
  GIT_TAG ${TPV_MAGICENUM_VER}
  GIT_SHALLOW true
  SOURCE_DIR ${CMAKE_SOURCE_DIR}/projects/magic_enum
  BINARY_DIR ${BUILDS_DIR}/magic_enum
  CMAKE_ARGS
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}
  -DCMAKE_INSTALL_MESSAGE=${CMAKE_INSTALL_MESSAGE}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}

  -DMAGIC_ENUM_OPT_BUILD_EXAMPLES:BOOL=OFF
  -DMAGIC_ENUM_OPT_BUILD_TESTS:BOOL=OFF
)

FetchContent_Declare(imgui
  GIT_REPOSITORY https://github.com/ocornut/imgui.git
  GIT_TAG ${TPV_IMGUI_VER}
  GIT_SHALLOW true
  SOURCE_DIR ${CMAKE_SOURCE_DIR}/projects/imgui
)
FetchContent_MakeAvailable(imgui)

add_library(imgui STATIC
  ${imgui_SOURCE_DIR}/imgui_draw.cpp
  ${imgui_SOURCE_DIR}/imgui_tables.cpp
  ${imgui_SOURCE_DIR}/imgui_widgets.cpp
  ${imgui_SOURCE_DIR}/imgui_demo.cpp
  ${imgui_SOURCE_DIR}/imgui.cpp

  ${imgui_SOURCE_DIR}/backends/imgui_impl_sdl3.cpp
  ${imgui_SOURCE_DIR}/backends/imgui_impl_vulkan.cpp
  ${imgui_SOURCE_DIR}/backends/imgui_impl_sdlrenderer3.cpp
)

set_target_properties(imgui
  PROPERTIES
  LIBRARY_OUTPUT_DIRECTORY "${INSTALL_DIR}/bin"
  ARCHIVE_OUTPUT_DIRECTORY "${INSTALL_DIR}/lib"
  PDB_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/"
)

install(FILES
  ${CMAKE_SOURCE_DIR}/projects/imgui/imgui.h
  ${CMAKE_SOURCE_DIR}/projects/imgui/imgui_internal.h
  ${CMAKE_SOURCE_DIR}/projects/imgui/imconfig.h
  ${CMAKE_SOURCE_DIR}/projects/imgui/imstb_rectpack.h
  ${CMAKE_SOURCE_DIR}/projects/imgui/imstb_textedit.h
  ${CMAKE_SOURCE_DIR}/projects/imgui/imstb_truetype.h

  ${CMAKE_SOURCE_DIR}/projects/imgui/backends/imgui_impl_sdl3.h
  ${CMAKE_SOURCE_DIR}/projects/imgui/backends/imgui_impl_vulkan.h
  ${CMAKE_SOURCE_DIR}/projects/imgui/backends/imgui_impl_sdlrenderer3.h

  DESTINATION ${INSTALL_DIR}/include/imgui
)

target_include_directories(imgui PRIVATE
  ${CMAKE_SOURCE_DIR}/projects/imgui/
  ${INSTALL_DIR}/include/
  ${Vulkan_INCLUDE_DIR}
)

add_dependencies(imgui sdl_project)
