name: build

on:
  workflow_dispatch:

jobs:
  build:
      name: ${{ matrix.config.build_type }} build for ${{ matrix.config.name }}
      strategy:
        fail-fast: false
        matrix:
          config:
            - name: Windows
              os: windows-latest
              preparation: ''
              build_type: Release
            - name: Linux
              os: ubuntu-latest
              preparation: 'sudo apt update -y && sudo apt install -y ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev'
              build_type: Release
            - name: Windows
              os: windows-latest
              preparation: ''
              build_type: Debug
            - name: Linux
              os: ubuntu-latest
              preparation: 'sudo apt update -y && sudo apt install -y ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev'
              build_type: Debug

      runs-on: ${{ matrix.config.os }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v7
          with:
            submodules: recursive

        - name: Run preparation command
          run: ${{ matrix.config.preparation }}

        - name: Detect MSVC
          uses: igor725/msvc-dev-cmd@v1
          if: ${{ matrix.config.name == 'Windows' }}
          with:
            arch: x86_64

        - name: Set up Clang
          uses: egor-tensin/setup-clang@23bc15cd4207e45f1566447deb48f4ff3ef932cb
          id: find-clang
          with:
            version: 21
            platform: x64

        - name: Prepare OpenSSL (Linux)
          if: ${{ matrix.config.name == 'Linux' }}
          shell: bash
          run: ./prepare_openssl.sh "_build/_Release/install" "${{ matrix.config.build_type }}"

        - name: Prepare OpenSSL (Windows)
          if: ${{ matrix.config.name == 'Windows' }}
          shell: cmd
          run: .\prepare_openssl.bat "_build\_Release\install" "${{ matrix.config.build_type }}"

        - name: Prepare boost
          shell: bash
          run: ./prepare_boost.sh

        - name: Prepare Vulkan SDK
          uses: jakoch/install-vulkan-sdk-action@37effcfa045411f8bfbbda26df2fd1b3bf3436fa
          with:
            vulkan_version: 1.4.335.0
            install_runtime: true
            cache: true

        - name: Configure
          run: cmake -S. -B_build/_Release -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DCMAKE_C_COMPILER=${{ steps.find-clang.outputs.clang }} -DCMAKE_CXX_COMPILER=${{ steps.find-clang.outputs.clangxx }}

        - name: Build
          run: cmake --build _build/_Release -j4

        - name: Install
          run: cmake --install _build/_Release

        - name: Zip it up
          working-directory: _build/_Release
          run: |
            7z a psOff-3rd-${{ matrix.config.name }}-${{ matrix.config.build_type }}.7z -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on ./install/* -xr!licenses

        - name: Upload artifacts
          uses: actions/upload-artifact@v7
          with:
            name: psOff-3rd-${{ matrix.config.name }}-${{ matrix.config.build_type }}
            path: _build/_Release/psOff-3rd-${{ matrix.config.name }}-${{ matrix.config.build_type }}.7z
